version: "3.7"
services:
  # quarkus:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #     args:
  #       - ARTIFACT_DIR=/home/usuario/projeto/target
  #   ports:
  #     - "8080:8080"
  #     - "5005:5005"
  #   environment:
  #     - QUARKUS_DEBUG=true
  #     - JAVA_OPTS=-Xmx512m -Xms128m -XX:PermSize=64m -XX:MaxPermSize=128m
  #   depends_on:
  #     - spendingdb
  spendingdb:
    environment: 
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=spendingdb
      - POSTGRES_USER=marco
    ports: 
      - "5433:5432"
    image: postgres:10-alpine
    volumes: 
      - db-data:/var/lib/postgresql/data

volumes: 
  db-data: